class AddAllToEkrps < ActiveRecord::Migration[5.2]
  def change
    add_column :ekrps, :exm, :string
    add_column :ekrps, :aa, :string
    add_column :ekrps, :ab, :string
    add_column :ekrps, :ac, :string
    add_column :ekrps, :ad, :string
    add_column :ekrps, :ae, :string
    add_column :ekrps, :af, :string
    add_column :ekrps, :ag, :string
    add_column :ekrps, :ah, :string
    add_column :ekrps, :ai, :string
    add_column :ekrps, :aj, :string
    add_column :ekrps, :ak, :string
    add_column :ekrps, :al, :string
    add_column :ekrps, :am, :string
    add_column :ekrps, :an, :string
    add_column :ekrps, :ao, :string
    add_column :ekrps, :ap, :string
    add_column :ekrps, :aq, :string
    add_column :ekrps, :ar, :string
    add_column :ekrps, :as, :string
    add_column :ekrps, :at, :string
    add_column :ekrps, :au, :string
    add_column :ekrps, :av, :string
    add_column :ekrps, :aw, :string
    add_column :ekrps, :ax, :string
    add_column :ekrps, :ay, :string
    add_column :ekrps, :az, :string
    add_column :ekrps, :ba, :string
    add_column :ekrps, :bb, :string
    add_column :ekrps, :bc, :string
    add_column :ekrps, :bd, :string
    add_column :ekrps, :be, :string
    add_column :ekrps, :bf, :string
    add_column :ekrps, :bg, :string
    add_column :ekrps, :bh, :string
    add_column :ekrps, :bi, :string
    add_column :ekrps, :bj, :string
    add_column :ekrps, :bk, :string
    add_column :ekrps, :bl, :string
    add_column :ekrps, :bm, :string
    add_column :ekrps, :bn, :string
    add_column :ekrps, :bo, :string
    add_column :ekrps, :bp, :string
    add_column :ekrps, :bq, :string
    add_column :ekrps, :br, :string
    add_column :ekrps, :bs, :string
    add_column :ekrps, :bt, :string
    add_column :ekrps, :bu, :string
    add_column :ekrps, :bv, :string
    add_column :ekrps, :bw, :string
    add_column :ekrps, :bx, :string
    add_column :ekrps, :by, :string
    add_column :ekrps, :bz, :string
    add_column :ekrps, :ca, :string
    add_column :ekrps, :cb, :string
    add_column :ekrps, :cc, :string
    add_column :ekrps, :cd, :string
    add_column :ekrps, :ce, :string
    add_column :ekrps, :cf, :string
    add_column :ekrps, :cg, :string
    add_column :ekrps, :ch, :string
    add_column :ekrps, :ci, :string
    add_column :ekrps, :cj, :string
    add_column :ekrps, :ck, :string
    add_column :ekrps, :cl, :string
    add_column :ekrps, :cm, :string
    add_column :ekrps, :cn, :string
    add_column :ekrps, :co, :string
    add_column :ekrps, :cp, :string
  end
end
